#!/usr/bin/env python
# Other special characters'
"""Special images.

G for Green
R for Red
O for Orange
Anything else is ignored.
"""

special = {
    'smile': ('Smilie with circle around it', [
        '  GGGG  ',
        ' G    G ',
        'G G  G G',
        'G      G',
        'G G  G G',
        'G  GG  G',
        ' G    G ',
        '  GGGG  ',
    ]),
    'smilie': ('Green smilie with no circle', [
        ' GG  GG ',
        ' GG  GG ',
        '        ',
        '   GG   ',
        'G  GG  G',
        'GG    GG',
        'GGGGGGGG',
        '  GGGG  ',
    ]),
    'frownie': ('Red frown with no cirle', [
        ' RR  RR ',
        ' RR  RR ',
        '        ',
        '   RR   ',
        '        ',
        ' RRRRRR ',
        'RRRRRRRR',
        'R      R',
    ]),
    'humph': ('Neutral expression face', [
        ' OO  OO ',
        ' OO  OO ',
        '        ',
        '   OO   ',
        '   OO   ',
        '        ',
        ' OOOOOO ',
        ' OOOOOO ',
    ]),
    'sad': ('Sad red smilie with circle around it', [
        '  RRRR  ',
        ' R    R ',
        'R R  R R',
        'R      R',
        'R  RR  R',
        'R R  R R',
        ' R    R ',
        '  RRRR  ',
    ]),
    'green': ('Solid green', [
        'GGGGGGGG',
        'GGGGGGGG',
        'GGGGGGGG',
        'GGGGGGGG',
        'GGGGGGGG',
        'GGGGGGGG',
        'GGGGGGGG',
        'GGGGGGGG',
    ]),
    'check': ('Check mark', [
        '      GG',
        '      GG',
        '     GG ',
        '     GG ',
        '    GG  ',
        'GG  GG  ',
        ' GGGG   ',
        '  GG    ',
    ]),
    'ex': ('X mark', [
        'R      R',
        ' R    R ',
        '  R  R  ',
        '   RR   ',
        '   RR   ',
        '  R  R  ',
        ' R    R ',
        'R      R',
    ]),
    'note': ('Musical Note', [
        '  GGGGGG',
        '  GGGGGG',
        '  GGGGGG',
        '  G    G',
        '  G    G',
        '  G    G',
        'GGG  GGG',
        'GGG  GGG',

    ]),
    'heart': ('Red heart', [
        '        ',
        '  RR RR ',
        ' RRRRRRR',
        ' RRRRRRR',
        '  RRRRR ',
        '   RRR  ',
        '    R   ',
        '        ',
    ]),
    'right': ('Right triangle \u25B6', [
        'G       ',
        'GG      ',
        'GGGG    ',
        'GGGGGG  ',
        'GGGGGGGG',
        'GGGGGG  ',
        'GGGG    ',
        'GG      ',
        'G       ',
    ]),
    'red': ('Solid red', [
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
    ]),
    'orange': ('Solid orange', [
        'OOOOOOOO',
        'OOOOOOOO',
        'OOOOOOOO',
        'OOOOOOOO',
        'OOOOOOOO',
        'OOOOOOOO',
        'OOOOOOOO',
        'OOOOOOOO',
    ]),
    'hex1': ('King Wen sequence 1 (Creative Power)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex2': ('King Wen sequence 2 (Natural Response)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex3': ('King Wen sequence 3 (Difficult Beginnings)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex4': ('King Wen sequence 4 (Inexperience)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex5': ('King Wen sequence 5 (Calculated Waiting)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex6': ('King Wen sequence 6 (Conflict)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex7': ('King Wen sequence 7 (Collective Force)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex8': ('King Wen sequence 8 (Unity)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex9': ('King Wen sequence 9 (Restrained)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex10': ('King Wen sequence 10 (Conduct)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex11': ('King Wen sequence 11 (Prospering)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex12': ('King Wen sequence 12 (Stagnation)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex13': ('King Wen sequence 13 (Community)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex14': ('King Wen sequence 14 (Sovereignty)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex15': ('King Wen sequence 15 (Moderation)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex16': ('King Wen sequence 16 (Harmonize)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex17': ('King Wen sequence 17 (Adapting)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex18': ('King Wen sequence 18 (Repair)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex19': ('King Wen sequence 19 (Promotion)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex20': ('King Wen sequence 20 (Contemplating)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex21': ('King Wen sequence 21 (Reform)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex22': ('King Wen sequence 22 (Grace)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex23': ('King Wen sequence 23 (Deterioration)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex24': ('King Wen sequence 24 (Returning)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex25': ('King Wen sequence 25 (Innocence)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex26': ('King Wen sequence 26 (Potential Energy)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex27': ('King Wen sequence 27 (Nourishing)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex28': ('King Wen sequence 28 (Critical Mass)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex29': ('King Wen sequence 29 (Danger)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex30': ('King Wen sequence 30 (Synergy)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex31': ('King Wen sequence 31 (Attraction)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex32': ('King Wen sequence 32 (Continuing)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex33': ('King Wen sequence 33 (Retreat)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex34': ('King Wen sequence 34 (Great Power)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex35': ('King Wen sequence 35 (Progress)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex36': ('King Wen sequence 36 (Censorship)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex37': ('King Wen sequence 37 (Family)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex38': ('King Wen sequence 38 (Contradiction)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex39': ('King Wen sequence 39 (Obstacles)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex40': ('King Wen sequence 40 (Liberation)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex41': ('King Wen sequence 41 (Decline)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex42': ('King Wen sequence 42 (Benefit)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex43': ('King Wen sequence 43 (Resolution)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex44': ('King Wen sequence 44 (Temptation)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex45': ('King Wen sequence 45 (Assembling)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex46': ('King Wen sequence 46 (Advancement)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex47': ('King Wen sequence 47 (Adversity)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex48': ('King Wen sequence 48 (The Source)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex49': ('King Wen sequence 49 (Revolution)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex50': ('King Wen sequence 50 (Cosmic Order)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex51': ('King Wen sequence 51 (Shocking)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex52': ('King Wen sequence 52 (Meditation)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex53': ('King Wen sequence 53 (Developing)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex54': ('King Wen sequence 54 (Subordinate)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex55': ('King Wen sequence 55 (Zenith)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex56': ('King Wen sequence 56 (Traveling)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex57': ('King Wen sequence 57 (Penetrating Influence)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex58': ('King Wen sequence 58 (Encouraging)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex59': ('King Wen sequence 59 (Reuniting)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex60': ('King Wen sequence 60 (Limitations)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex61': ('King Wen sequence 61 (Insight)', [
        '        ',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex62': ('King Wen sequence 62 (Conscientiousness)', [
        '        ',
        'RRR  RRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRR  RRR',
        '        ',
    ]),
    'hex63': ('King Wen sequence 63 (After the End)', [
        '        ',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        '        ',
    ]),
    'hex64': ('King Wen sequence 64 (Before the End)', [
        '        ',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        'RRRRRRRR',
        'RRR  RRR',
        '        ',
    ]),
}
